   
    logical :: bool1                     !! logical :: bool1
    logical :: bool2                     !! logical :: bool2
    logical :: bool3                     !! logical :: bool3
    logical :: bool4                     !! logical :: bool4
    logical :: boolarray1(2)             !! logical :: boolarray1(2)
    logical, dimension(3) :: boolarray2  !! logical, dimension(3) :: boolarray2

    integer :: int1                    !! integer :: int1
    integer :: int2                    !! integer :: int2
    integer :: int3                    !! integer :: int3
    integer :: int4                    !! integer :: int4
    integer(8) :: int5                 !! integer(8) :: int5
    integer(kind=long) :: int6         !! integer(kind=long) :: int6
    integer :: intarray1(3)            !! integer :: intarray1(3) 
    integer, dimension(4) :: intarray2 !! integer, dimension(4) :: intarray2 

    real :: real1                    !! real :: real1
    real :: real2                    !! real :: real2
    real :: real3                    !! real :: real3
    real :: real4                    !! real :: real4
    real(8) :: real5                 !! real(8) :: real5
    real(kind=dp) :: real6           !! real(kind=dp) :: real6
    real :: realarray1(5)            !! real :: realarray1(5)
    real, dimension(6) :: realarray2 !! real, dimension(6) :: realarray2

    character :: a_char                         !! character :: a_char
    character(20) :: string1                    !! character(20) :: string1
    character(21) :: string2                    !! character(21) :: string2
    character(22), dimension(2) :: stringarray1 !! character(22), dimension(2) :: stringarray1
    character(len=23) :: stringarray2(3)        !! character(len=23) :: stringarray2(3)

