main – FORD Fortran Autodoc exerciser
main Program
222 statements
Source File
Uses
kinds_mod
a_mod
classes_mod
FORD Fortran autodoc exerciser program
declares/defines module-level variables/procedures declares/defines type-bound procedures and uses submodules
Calls
Contents
Variables
logical_value int_value real_value bool1 bool2 bool3 bool4 boolarray1 boolarray2 int1 int2 int3 int4 int5 int6 intarray1 intarray2 real1 real2 real3 real4 real5 real6 realarray1 realarray2 a_char string1 string2 stringarray1 stringarray2 stored_int stored_real stored_complex
Interfaces
non_module_file_procedure
Functions
main_dummy_vars_fcn1 main_dummy_vars_fcn2 main_dummy_vars_fcn3
Subroutines
main_dummy_vars_sub
Variables
Type Attributes Name Initial
logical :: logical_value
pre-doc comment
integer :: int_value
post-doc comment
real :: real_value
pre-doc comment post-doc comment
logical :: bool1
logical :: bool1
logical :: bool2
logical :: bool2
logical :: bool3
logical :: bool3
logical :: bool4
logical :: bool4
logical :: boolarray1(2)
logical :: boolarray1(2)
logical, dimension(3) :: boolarray2
logical, dimension(3) :: boolarray2
integer :: int1
integer :: int1
integer :: int2
integer :: int2
integer :: int3
integer :: int3
integer :: int4
integer :: int4
integer(kind=8) :: int5
integer(8) :: int5
integer(kind=long) :: int6
integer(kind=long) :: int6
integer :: intarray1(3)
integer :: intarray1(3)
integer, dimension(4) :: intarray2
integer, dimension(4) :: intarray2
real :: real1
real :: real1
real :: real2
real :: real2
real :: real3
real :: real3
real :: real4
real :: real4
real(kind=8) :: real5
real(8) :: real5
real(kind=dp) :: real6
real(kind=dp) :: real6
real :: realarray1(5)
real :: realarray1(5)
real, dimension(6) :: realarray2
real, dimension(6) :: realarray2
character :: a_char
character :: a_char
character(len=20) :: string1
character(20) :: string1
character(len=21) :: string2
character(21) :: string2
character(len=22), dimension(2) :: stringarray1
character(22), dimension(2) :: stringarray1
character(len=23) :: stringarray2(3)
character(len=23) :: stringarray2(3)
type(int_class_extended_t) :: stored_int
pre-doc comment post-doc comment
type(real_class_extended_t) :: stored_real
pre-doc comment post-doc comment
type(complex_class_extended_t) :: stored_complex
pre-doc comment post-doc comment
Interfaces
interface
subroutine non_module_file_procedure(int_value)
Arguments
Type Intent Optional Attributes Name
integer :: int_value
Functions
function main_dummy_vars_fcn1(bool1, bool2, bool3, bool4, boolarray1, boolarray2, int1, int2, int3, int4, int5, int6, intarray1, intarray2, real1, real2, real3, real4, real5, real6, realarray1, realarray2, a_char, string1, string2, stringarray1, stringarray2, output)
Main program function (return type defined in body) that exercises the dummy variables for autodoc program
Read more…
Arguments
Type Intent Optional Attributes Name
logical :: bool1
logical :: bool1
logical, intent(in) :: bool2
logical, intent(in) :: bool2
logical, intent(out) :: bool3
logical, intent(out) :: bool3
logical, intent(inout) :: bool4
logical, intent(inout) :: bool4
logical, intent(inout) :: boolarray1(2)
logical, intent(inout) :: boolarray1(2)
logical, intent(in), dimension(3) :: boolarray2
logical, dimension(3), intent(in) :: boolarray2
integer :: int1
integer :: int1
integer, intent(in) :: int2
integer, intent(in) :: int2
integer, intent(out) :: int3
integer, intent(out) :: int3
integer, intent(inout) :: int4
integer, intent(inout) :: int4
integer(kind=8), intent(in) :: int5
integer(8), intent(in) :: int5
integer(kind=long), intent(in) :: int6
integer(kind=long), intent(in) :: int6
integer, intent(inout) :: intarray1(3)
integer, intent(inout) :: intarray1(3)
integer, intent(in), dimension(4) :: intarray2
integer, dimension(4), intent(in) :: intarray2
real :: real1
real :: real1
real, intent(in) :: real2
real, intent(in) :: real2
real, intent(out) :: real3
real, intent(out) :: real3
real, intent(inout) :: real4
real, intent(inout) :: real4
real(kind=8), intent(in) :: real5
real(8), intent(in) :: real5
real(kind=dp), intent(in) :: real6
real(kind=dp), intent(in) :: real6
real, intent(inout) :: realarray1(5)
real, intent(inout) :: realarray1(5)
real, intent(in), dimension(6) :: realarray2
real, dimension(6), intent(in) :: realarray2
character, intent(in) :: a_char
character, intent(in) :: a_char
character(len=20), intent(in) :: string1
character(20), intent(in) :: string1
character(len=21), intent(out) :: string2
character(21), intent(out) :: string2
character(len=22), intent(inout), dimension(2) :: stringarray1
character(22), dimension(2), intent(inout) :: stringarray1
character(len=23), intent(inout) :: stringarray2(3)
character(len=23), intent(inout) :: stringarray2(3)
character(len=*), intent(in) :: output
What to output character(len=*), intent(in) :: output
Return Value integer
Just wanted a function. Return value not meaningful.
function main_dummy_vars_fcn2(bool1, bool2, bool3, bool4, boolarray1, boolarray2, int1, int2, int3, int4, int5, int6, intarray1, intarray2, real1, real2, real3, real4, real5, real6, realarray1, realarray2, a_char, string1, string2, stringarray1, stringarray2, output)
Main program function (return type defined in first line) that exercises the dummy variables for autodoc program
Read more…
Arguments
Type Intent Optional Attributes Name
logical :: bool1
logical :: bool1
logical, intent(in) :: bool2
logical, intent(in) :: bool2
logical, intent(out) :: bool3
logical, intent(out) :: bool3
logical, intent(inout) :: bool4
logical, intent(inout) :: bool4
logical, intent(inout) :: boolarray1(2)
logical, intent(inout) :: boolarray1(2)
logical, intent(in), dimension(3) :: boolarray2
logical, dimension(3), intent(in) :: boolarray2
integer :: int1
integer :: int1
integer, intent(in) :: int2
integer, intent(in) :: int2
integer, intent(out) :: int3
integer, intent(out) :: int3
integer, intent(inout) :: int4
integer, intent(inout) :: int4
integer(kind=8), intent(in) :: int5
integer(8), intent(in) :: int5
integer(kind=long), intent(in) :: int6
integer(kind=long), intent(in) :: int6
integer, intent(inout) :: intarray1(3)
integer, intent(inout) :: intarray1(3)
integer, intent(in), dimension(4) :: intarray2
integer, dimension(4), intent(in) :: intarray2
real :: real1
real :: real1
real, intent(in) :: real2
real, intent(in) :: real2
real, intent(out) :: real3
real, intent(out) :: real3
real, intent(inout) :: real4
real, intent(inout) :: real4
real(kind=8), intent(in) :: real5
real(8), intent(in) :: real5
real(kind=dp), intent(in) :: real6
real(kind=dp), intent(in) :: real6
real, intent(inout) :: realarray1(5)
real, intent(inout) :: realarray1(5)
real, intent(in), dimension(6) :: realarray2
real, dimension(6), intent(in) :: realarray2
character, intent(in) :: a_char
character, intent(in) :: a_char
character(len=20), intent(in) :: string1
character(20), intent(in) :: string1
character(len=21), intent(out) :: string2
character(21), intent(out) :: string2
character(len=22), intent(inout), dimension(2) :: stringarray1
character(22), dimension(2), intent(inout) :: stringarray1
character(len=23), intent(inout) :: stringarray2(3)
character(len=23), intent(inout) :: stringarray2(3)
character(len=*), intent(in) :: output
What to output character(len=*), intent(in) :: output
Return Value integer
function main_dummy_vars_fcn3(bool1, bool2, bool3, bool4, boolarray1, boolarray2, int1, int2, int3, int4, int5, int6, intarray1, intarray2, real1, real2, real3, real4, real5, real6, realarray1, realarray2, a_char, string1, string2, stringarray1, stringarray2, output) result(val)
Main program function (return type and result name defined in first line) that exercises the dummy variables for autodoc program
Read more…
Arguments
Type Intent Optional Attributes Name
logical :: bool1
logical :: bool1
logical, intent(in) :: bool2
logical, intent(in) :: bool2
logical, intent(out) :: bool3
logical, intent(out) :: bool3
logical, intent(inout) :: bool4
logical, intent(inout) :: bool4
logical, intent(inout) :: boolarray1(2)
logical, intent(inout) :: boolarray1(2)
logical, intent(in), dimension(3) :: boolarray2
logical, dimension(3), intent(in) :: boolarray2
integer :: int1
integer :: int1
integer, intent(in) :: int2
integer, intent(in) :: int2
integer, intent(out) :: int3
integer, intent(out) :: int3
integer, intent(inout) :: int4
integer, intent(inout) :: int4
integer(kind=8), intent(in) :: int5
integer(8), intent(in) :: int5
integer(kind=long), intent(in) :: int6
integer(kind=long), intent(in) :: int6
integer, intent(inout) :: intarray1(3)
integer, intent(inout) :: intarray1(3)
integer, intent(in), dimension(4) :: intarray2
integer, dimension(4), intent(in) :: intarray2
real :: real1
real :: real1
real, intent(in) :: real2
real, intent(in) :: real2
real, intent(out) :: real3
real, intent(out) :: real3
real, intent(inout) :: real4
real, intent(inout) :: real4
real(kind=8), intent(in) :: real5
real(8), intent(in) :: real5
real(kind=dp), intent(in) :: real6
real(kind=dp), intent(in) :: real6
real, intent(inout) :: realarray1(5)
real, intent(inout) :: realarray1(5)
real, intent(in), dimension(6) :: realarray2
real, dimension(6), intent(in) :: realarray2
character, intent(in) :: a_char
character, intent(in) :: a_char
character(len=20), intent(in) :: string1
character(20), intent(in) :: string1
character(len=21), intent(out) :: string2
character(21), intent(out) :: string2
character(len=22), intent(inout), dimension(2) :: stringarray1
character(22), dimension(2), intent(inout) :: stringarray1
character(len=23), intent(inout) :: stringarray2(3)
character(len=23), intent(inout) :: stringarray2(3)
character(len=*), intent(in) :: output
What to output character(len=*), intent(in) :: output
Return Value integer
Subroutines
subroutine main_dummy_vars_sub(bool1, bool2, bool3, bool4, boolarray1, boolarray2, int1, int2, int3, int4, int5, int6, intarray1, intarray2, real1, real2, real3, real4, real5, real6, realarray1, realarray2, a_char, string1, string2, stringarray1, stringarray2, output)
Main program subroutine that exercises the dummy variables for autodoc program
Read more…
Arguments
Type Intent Optional Attributes Name
logical :: bool1
logical :: bool1
logical, intent(in) :: bool2
logical, intent(in) :: bool2
logical, intent(out) :: bool3
logical, intent(out) :: bool3
logical, intent(inout) :: bool4
logical, intent(inout) :: bool4
logical, intent(inout) :: boolarray1(2)
logical, intent(inout) :: boolarray1(2)
logical, intent(in), dimension(3) :: boolarray2
logical, dimension(3), intent(in) :: boolarray2
integer :: int1
integer :: int1
integer, intent(in) :: int2
integer, intent(in) :: int2
integer, intent(out) :: int3
integer, intent(out) :: int3
integer, intent(inout) :: int4
integer, intent(inout) :: int4
integer(kind=8), intent(in) :: int5
integer(8), intent(in) :: int5
integer(kind=long), intent(in) :: int6
integer(kind=long), intent(in) :: int6
integer, intent(inout) :: intarray1(3)
integer, intent(inout) :: intarray1(3)
integer, intent(in), dimension(4) :: intarray2
integer, dimension(4), intent(in) :: intarray2
real :: real1
real :: real1
real, intent(in) :: real2
real, intent(in) :: real2
real, intent(out) :: real3
real, intent(out) :: real3
real, intent(inout) :: real4
real, intent(inout) :: real4
real(kind=8), intent(in) :: real5
real(8), intent(in) :: real5
real(kind=dp), intent(in) :: real6
real(kind=dp), intent(in) :: real6
real, intent(inout) :: realarray1(5)
real, intent(inout) :: realarray1(5)
real, intent(in), dimension(6) :: realarray2
real, dimension(6), intent(in) :: realarray2
character, intent(in) :: a_char
character, intent(in) :: a_char
character(len=20), intent(in) :: string1
character(20), intent(in) :: string1
character(len=21), intent(out) :: string2
character(21), intent(out) :: string2
character(len=22), intent(inout), dimension(2) :: stringarray1
character(22), dimension(2), intent(inout) :: stringarray1
character(len=23), intent(inout) :: stringarray2(3)
character(len=23), intent(inout) :: stringarray2(3)
character(len=*), intent(in) :: output
What to output character(len=*), intent(in) :: output
Call graph
main calls main_dummy_vars_sub, main_dummy_vars_fcn2, a_mod_dummy_vars_sub, a_mod_dummy_vars_fcn1, main_dummy_vars_fcn1, main_dummy_vars_fcn3, a_mod_dummy_vars_fcn2, a_mod_dummy_vars_fcn3, non_module_file_procedure